print("""
sssssssssssssooooooooooooo++ooooosyyyhhhhhhhyyyhhhdhhyysssyhdddddddddddmddNNMMNM
sssssssssssoooooooooooooooosyhddmmmmmmmmmmmmmmmmmmmmdddmmmddddddddddddddmdmNNMNM
ssssssssssssooooooooooosyhdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddddddmmmNMMNM
sssssssssssoooooooooshdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdhhdddddmmmmmNMMNM
ssssssssssooooooosydmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddhdddmmmmNMNNM
ssssssssoooooooshdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddhddmmNNNMMNM
sssssssssoooooydmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdhdmmmNNMNNM
sssssssssssssdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmNNNNNM
sssssssssssydmmmmmmmmmmmmmdmmmmmmmmmmmmmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNM
ssssossssshmmmmmmmmmmmmmmsdmmmmmmmdmmddmmmmmmmmdNmmmmmmmmdmmmmmmmmmmmmmmmmNNNNNM
ssssssssshmmmmmmmmmmmmmmysmmmddmmdymdydmdmddmmmydNmmmmmmmhhmmmmmmdmmmmmmmNNNNNNM
ssssssssymmmmmmmmmmmmmmhosmmmdydmhydyyddydhmmmdoomNmmmmmmdydmmmmmhdmmmmmmNNNNNmN
ssssssssdmmdmmmmmdmmmmdo+ymmmdyhdyyhyydyyhhmmmh::sNNmmmmmmhydmmmmyhmmmmmmmNNNNmN
sssssssydmmhdmmmhdmmmms/-ommmdyyhyyyyyyhdydddm+--:sNmmmmmmdyymhdmhydmmmmmmmNNNNN
sssoooodymhhdhmdhmmmmh+--/ddddydyyyydyydmdmddy/////yNmmmmmmyhdhymhyhNmmmmmmmNNNN
sssooosdydyhyydhdmmddo//:/hdddymyyyhmhhmmmmdd:-.---/yNmmmmmhhhhyhyyhmNmmmmmmmNNN
sssooohhyhyyyyhhmmmmh+:---/dmmhmdyydmdmmmmddo.......-smmmmmdhdhhyyyhmNmmmmmmmNNN
ssoooodhyyyydyydmmdd+--.---dmmmmmhymmmmmmmdy--://+/:--ommmmddmydyyhddNmmmmmmmmNN
sssoosmhyyyhmhydmmdy-......ommmmmmhmmmmmmdmooso+/++sys+sNmmmmmhdhyhmmNNmmmmmmmmN
ssooosmyhyydmdhmmdm/:+ooooo+dmmmmmmmmmmyddd+:..```.--/shhNmmmmmmdyhmmNNmmmmmmmmN
ssssoymyddhmmmdmmddsso/:::/ohmmmmmmmmmd/hd/.````.ohdy-./hhNmmmmmmydmmNNmNmmmmmmm
ssssshmhmmdmmmmmmmh/-..`.:/:-yddmmmmddh.yh``````/mmNNy``:sommmmmmhmmmNNNNmmmmmmm
sssssdmhmmmmmmmmmm-.```.hmmmo.sodmmdddo./y``````ommmNm.``o.sdmmmmmmmmNNNNmmmmmmm
sssssdmdmmmmmmmmmh`````:NNNNm-:/sdhddd-..o``````-dmmmd.``o.ommmmmmmmmNNNNmmmmmmm
sssssdmmmmmmmmmdN+`````.mmNNN+./.o/ydh.../:``````-syo:``.o.omdmmmmmmmNNNNmmmmmmm
sssssmmmmmmmmmmmN:``````/dmmd-./...-yo....+.````````````//.omdmmmmmmmNNNNNmmmmmm
ssooodmmmmmmmmmmm+```````.::.`:/....-:....-+```````````-o..+ddmmmmNmmNNNNNNmmmmm
ooooodmmmmmmmmmmd/+``````````.o............:/.``````..:+...+mdmmmmNmmNNNNNNmmmmm
ooooohmmmmmmmmmNh.:+-``````.-/-..............:/:::::-/-....+mmmmmmNmmNNNNNNNmmmm
oooooymmmmmmmmmNm:.-/+/-/:-:-.....--.............-.........oddmmmmNmNNNNNNNNNmmm
ooooosmmmmmmmmmNms...--.-..................................oddmmmmNmNNNNNNNNNmmm
oooooommmmmmmmmNhs-.................................-......sdmmmmNNmNNNNNNNNNNmm
oooooodmmmmmmmmNhs:............................--:://-.....ydmmmmNNmNNNNNNNNNNNm
oooooohmmmmmmmmNdo+.......-//:-............--:--...........hdmmmmNNNNNNNNNNNNNNm
ooooooymmmmmmmmNm+y:.......----:::-....--::-.............:smmmmmmNNNNNNNNNNNNNNN
oooooosmmmmmmmmNNo+s/:/:-.........------..............-:smNmmmmmmNNNNNNNNNNNNNNN
ooooooohmmmmmmmNNs++o::-/:.........................-:+oosmNmmmmmmNNNNNNNNNNNNNNN
ooooooosmmmmmmmNNy+++.-:.o-....................-:oooooooosmmmmmmNNNNNNNNNNNNNNNN
oooooooodmmmmmmNNh+++-:-.o/+//:-..........--/ohmdysooooosodmmmmmNNNm+sdNNNNNNmmm
oo++oooosmmmmmmNNm+o-::..o/////++///---/oydmNmdyysooooos::mmmmmmNNNy:/+oso+//:::
++o++++++hddmmmmNNo+....-o////////+/::/dddddyyyyysooos+--ommmmmmNNNo/:----------
++++++++oso/sddmNNy-....+o++///+o+----:sossooosoooooo:---ymmmmmNNNy-------------
++++++++o-:/.oddNd:....//-oo++o+-----.ooooosoooooos+----:dmmmmmNNN/-------/osooo
++++++++++/-.-dds-..../:.os+/:--------soooooooooos:-----/mmmmmNNNh-----://::/+++
+++++++++o...-s:...../:-.s------------+:/+oooooos:------ommmmmNNN/---//:-://///:
++++++++++.:/:.....-+---.o------------+..-:/+//o--------ymmmmmNNy:///-:+/:------
""")
